### PR TITLE
Update mParticle submodule to 7.15.8

### PR DESCRIPTION
**Pull request by gvillanueva17**
Update mParticle to 7.15.8 to get rid of UIWebView

### CODE REVIEW

**Comment by vinaisuresh9** [comment]
Sup peeps. I should probably not have access to this 😛

**Comment by gvillanueva17** [comment]
Oh hey @vinaisuresh9!

**Comment by onyxmueller** [comment]
@vinaisuresh9 It's open-source/public.

**Comment by vinaisuresh9** [comment]
well, then that's on me 😅

**Comment by smehus** [comment]
@gvillanueva17  Can you create a develop branch and point this towards that

**Comment by gvillanueva17** [comment]
@smehus done

**Pull request merged**
